package Model;
// Generated 12-mar-2021 1:09:04 by Hibernate Tools 4.3.1



/**
 * Juegos generated by hbm2java
 */
public class Juegos  implements java.io.Serializable {


     private int id;
     private String nombre;
     private Integer precio;
     private Integer totalPtos;
     private String dniCliente;

    public Juegos() {
    }

	
    public Juegos(int id) {
        this.id = id;
    }
    public Juegos(int id, String nombre, Integer precio, Integer totalPtos, String dniCliente) {
       this.id = id;
       this.nombre = nombre;
       this.precio = precio;
       this.totalPtos = totalPtos;
       this.dniCliente = dniCliente;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Integer precio) {
        this.precio = precio;
    }
    public Integer getTotalPtos() {
        return this.totalPtos;
    }
    
    public void setTotalPtos(Integer totalPtos) {
        this.totalPtos = totalPtos;
    }
    public String getDniCliente() {
        return this.dniCliente;
    }
    
    public void setDniCliente(String dniCliente) {
        this.dniCliente = dniCliente;
    }




}


