package Model;
// Generated 12-mar-2021 1:09:04 by Hibernate Tools 4.3.1



/**
 * Jugadores generated by hbm2java
 */
public class Jugadores  implements java.io.Serializable {


     private String dni;
     private String nombre;
     private String pass;

    public Jugadores() {
    }

	
    public Jugadores(String dni) {
        this.dni = dni;
    }
    public Jugadores(String dni, String nombre, String pass) {
       this.dni = dni;
       this.nombre = nombre;
       this.pass = pass;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }




}


