package Model;
// Generated 12-mar-2021 1:09:04 by Hibernate Tools 4.3.1



/**
 * Partidas generated by hbm2java
 */
public class Partidas  implements java.io.Serializable {


     private int id;
     private Integer ptos;
     private Integer idJuegos;

    public Partidas() {
    }

	
    public Partidas(int id) {
        this.id = id;
    }
    public Partidas(int id, Integer ptos, Integer idJuegos) {
       this.id = id;
       this.ptos = ptos;
       this.idJuegos = idJuegos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getPtos() {
        return this.ptos;
    }
    
    public void setPtos(Integer ptos) {
        this.ptos = ptos;
    }
    public Integer getIdJuegos() {
        return this.idJuegos;
    }
    
    public void setIdJuegos(Integer idJuegos) {
        this.idJuegos = idJuegos;
    }




}


